name: Build N960N Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Install dependencies
      run: |
        sudo apt update

        sudo apt install -y \
          bc \
          bison \
          flex \
          build-essential \
          libssl-dev \
          libelf-dev \
          gcc-aarch64-linux-gnu \
          python3-pip \
          cpio \
          unzip


    - name: Download Kernel Source
      run: |
        pip3 install gdown

        gdown "https://drive.google.com/uc?id=1Cc3p0wqOXAAzgpxTvZf6oCv_YnU4tzl9" \
        -O Kernel.tar.gz


    - name: Extract Kernel
      run: |
        mkdir kernel

        tar -xzf Kernel.tar.gz -C kernel


    - name: Find and install defconfig
      run: |

        echo "=== Searching defconfig ==="

        CONFIG=$(find kernel \
        -type f \
        -name "exynos9810-crownlteks_defconfig_DriveDroid_stable" \
        | head -n 1)


        if [ -z "$CONFIG" ]; then

          echo "Defconfig not found inside kernel"

          echo "Searching all crown files:"
          find kernel -iname "*crownlteks*"

          exit 1

        fi


        echo "Found:"
        echo "$CONFIG"


        if [ "$CONFIG" != "kernel/arch/arm64/configs/exynos9810-crownlteks_defconfig_DriveDroid_stable" ]; then

          cp "$CONFIG" \
          kernel/arch/arm64/configs/exynos9810-crownlteks_defconfig_DriveDroid_stable

        fi


        echo "=== Check ==="

        ls -lh kernel/arch/arm64/configs/ | grep crownlteks



    - name: Fix sdcardfs
      run: |
        cd kernel

        sed -i '/source "fs\/sdcardfs\/Kconfig"/d' fs/Kconfig || true



    - name: Prepare config
      run: |

        cd kernel

        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-


        echo "=== Make defconfig ==="


        make O=out \
        exynos9810-crownlteks_defconfig_DriveDroid_stable



    - name: Enable USB Gadget
      run: |

        cd kernel


        scripts/config --file out/.config \
          -e USB_GADGET \
          -e USB_CONFIGFS \
          -e USB_CONFIGFS_MASS_STORAGE \
          -e USB_CONFIGFS_F_MTP \
          -e USB_CONFIGFS_F_ADB


        make O=out olddefconfig



    - name: Build Kernel
      run: |

        cd kernel

        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-


        make O=out -j$(nproc) Image.gz-dtb



    - name: Upload Kernel
      uses: actions/upload-artifact@v4

      with:

        name: N960N-kernel

        path: kernel/out/arch/arm64/boot/Image.gz-dtb
